name: 'Setup Ollama'
description: 'Setup Ollama'
runs:
  using: "composite"
  steps:
    - name: Install Ollama and start server
      shell: bash
      run: |
        curl -fsSL https://ollama.com/download/ollama-linux-amd64.tgz \
          | sudo tar zx -C /usr
        OLLAMA_HOST="localhost:55555" ollama serve &

    - name: Wait for Ollama server
      shell: bash
      run: |
        sleep 10
        time curl -i http://localhost:55555

    - name: Download granite3.3:2b model
      shell: bash
      run: |
        ollama pull granite3.3:2b

    - name: Wait for granite3.3:2b download
      shell: bash
      run: |
        sleep 10
        until ollama list granite3.3:2b
        do
          sleep 5
        done
