name: 'Setup intrinsics for Ollama'
description: 'Convert intrinsics and serve on Ollama'

inputs:
  HF_TOKEN:
    required: true

runs:
  using: "composite"
  steps:
    - name: Clone HF intrinsics repo
      shell: bash
      run: |
        git clone git@hf.co:ibm-granite/granite-lib-rag-r1.0
        cd granite-lib-rag-r1.0
        git fetch origin
        git pull origin refs/pr/4

    - name: List cloned files
      shell: bash
      run: ls -lah granite-lib-rag-r1.0

    - name: Deploy intrinsics on Ollama
      shell: bash
      run: |
        cd granite-lib-rag-r1.0
        bash run_ollama.sh

    - name: Clean up
      shell: bash
      run: |
        rm -rf granite-lib-rag-r1.0
