name: 'Setup intrinsics for Ollama'
description: 'Convert intrinsics and serve on Ollama'
runs:
  using: "composite"
  steps:
    - name: Setup Git credentials for HF
      shell: bash
      run: |
        git config --global credential.helper store
        echo "https://user:${HF_TOKEN}@huggingface.co" > ~/.git-credentials
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Clone HF intrinsics repo
      shell: bash
      run: |
        git clone -b feat/ollama-loras https://huggingface.co/generative-computing/rag-intrinsics-lib

    - name: List cloned files
      shell: bash
      run: ls -lah rag-intrinsics-lib

    - name: Convert weights to GGUF and deploy on Ollama
      shell: bash
      run: |
        cd rag-intrinsics-lib/_ollama
        bash convert_and_load_intrinsics.sh
