name: 'Setup intrinsics for Ollama'
description: 'Convert intrinsics and serve on Ollama'

inputs:
  HF_TOKEN:
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Git credentials for HF
      shell: bash
      run: |
        git config --global credential.helper store
        echo "https://user:${{ inputs.HF_TOKEN }}@huggingface.co" > ~/.git-credentials
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Clone HF intrinsics repo
      shell: bash
      run: |
        git clone https://huggingface.co/ibm-granite/granite-lib-rag-r1.0
        cd granite-lib-rag-r1.0
        git fetch origin
        git pull origin refs/pr/9

    - name: List cloned files
      shell: bash
      run: ls -lah granite-lib-rag-r1.0

    - name: Deploy intrinsics on Ollama
      shell: bash
      run: |
        cd granite-lib-rag-r1.0
        bash run_ollama.sh

    - name: Clean up
      shell: bash
      run: |
        rm -rf granite-lib-rag-r1.0
