name: 'Setup intrinsics for Ollama'
description: 'Convert intrinsics and serve on Ollama'
runs:
  using: "composite"
  steps:
    - name: Clone HF intrinsics repo
      shell: bash
      run: |
        HF_REPO="https://huggingface.co/generative-computing/rag-intrinsics-lib"
        git clone -b feat/ollama-loras https://user:$HF_TOKEN@${HF_REPO#https://}

    - name: List cloned files
      shell: bash
      run: ls -R rag-intrinsics-lib || true
