name: 'Setup intrinsics for Ollama'
description: 'Convert intrinsics and serve on Ollama'
runs:
  using: "composite"
  steps:
    - name: Clone HF intrinsics repo
      shell: bash
      run: |
        git clone -b feat/ollama-loras https://huggingface.co/generative-computing/rag-intrinsics-lib

    - name: List cloned files
      shell: bash
      run: ls -R rag-intrinsics-lib || true
